[package]
name = "alsa"
version = "0.1.4"
authors = ["David Henningsson <diwic@ubuntu.com>"]

description = "Thin but safe wrappers for ALSA (Linux sound API)"
repository = "https://github.com/diwic/alsa-rs"
documentation = "http://docs.rs/alsa"
keywords = ["ALSA", "audio", "sound"]
license = "Apache-2.0/MIT"

[dependencies]
libc = "0.2.7"
alsa-sys = "0.1.0"
bitflags = "0.5"
